### ISSUE TITLE
nix flow: "today" is always 1.1.1980

### ISSUE THREAD

**Issue by phip1611** [TUD-OS/latex-template#18]
@blitz When you initially created the Nix support, we all missed that the "today" date is 1.1.1980

<img width="678" alt="Bildschirmfoto 2023-01-21 um 15 02 45" src="https://user-images.githubusercontent.com/5737016/213870371-194acee5-2448-4d1e-a75b-95cfab0a067e.png">

Whats the best solution to that?

**Comment by blitz** [comment]
The best solution is to let the user specify the date that should be in the document and not rely on side effects in the build.

**Comment by phip1611** [comment]
Yikes, yes, you're right. I've it like this in my thesis as well.
